import { StyleSheet } from "react-native";
import { colors } from "../../theme/color";

export const styles = StyleSheet.create({
  scroll: { flex: 1 },
  content: { paddingHorizontal: 20, paddingBottom: 100 },
  screenTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: colors.textPrimary,
    letterSpacing: -0.5,
    marginBottom: 8,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
    marginBottom: 20,
  },
  greet: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: "800",
    letterSpacing: -0.5,
  },
  subGreet: { color: colors.textSecondary, marginTop: 6, fontSize: 15 },
  avatarSm: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
  },
  err: { color: colors.error, marginBottom: 12 },
  statsRow: { flexDirection: "row", gap: 10, marginBottom: 20 },
  statSk: { flex: 1, height: 88, borderRadius: 12 },
  scoreCardSk: { height: 160, borderRadius: 16, marginBottom: 24 },
  statPress: { flex: 1 },
  statCard: {
    flex: 1,
    backgroundColor: colors.surfaceAlt,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  statVal: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: "800",
    marginTop: 6,
  },
  statLab: { color: colors.textMuted, fontSize: 11, marginTop: 4 },
  atsCard: {
    flexDirection: "row",
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 16,
  },
  emptyScoreCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 24,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
  },
  emptyScoreTitle: {
    color: colors.textPrimary,
    fontWeight: "700",
    fontSize: 17,
    marginTop: 12,
  },
  emptyScoreSub: {
    color: colors.textSecondary,
    textAlign: "center",
    marginTop: 8,
    lineHeight: 22,
    fontSize: 15,
  },
  getStartedBtn: {
    marginTop: 16,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 14,
  },
  getStartedTxt: { color: colors.textPrimary, fontWeight: "700" },
  ringWrap: { justifyContent: "center" },
  atsTitle: { color: colors.textPrimary, fontWeight: "700", fontSize: 16 },
  tierPillWide: {
    alignSelf: "flex-start",
    marginTop: 8,
    marginBottom: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
  },
  tierPillTxt: { color: colors.textSecondary, fontSize: 12, fontWeight: "600" },
  reportBtn: { paddingVertical: 12, borderRadius: 14, alignItems: "center" },
  reportBtnText: { color: colors.textPrimary, fontWeight: "700" },
  sectionTitle: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginBottom: 12,
  },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: 12, marginBottom: 24 },
  actionCard: {
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
    minHeight: 100,
    gap: 8,
  },
  actionLab: { color: colors.textPrimary, fontWeight: "600", fontSize: 14 },
  tipCard: {
    width: 260,
    backgroundColor: colors.surfaceAlt,
    borderRadius: 16,
    padding: 16,
    marginRight: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  tipEmoji: { fontSize: 28, marginBottom: 8 },
  tipTitle: {
    color: colors.textPrimary,
    fontWeight: "700",
    marginBottom: 8,
    fontSize: 16,
  },
  tipBody: { color: colors.textSecondary, lineHeight: 22, fontSize: 14 },
});
