import { StyleSheet } from "react-native";
import type { AppTheme } from "../../theme";

export function createHomeStyles(theme: AppTheme) {
  return StyleSheet.create({
  scroll: { flex: 1 },
  content: { paddingHorizontal: 20, paddingBottom: 100 },
  screenTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: theme.textPrimary,
    letterSpacing: -0.5,
    marginBottom: 8,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
    marginBottom: 20,
  },
  greet: {
    color: theme.textPrimary,
    fontSize: 22,
    fontWeight: "800",
    letterSpacing: -0.5,
  },
  subGreet: { color: theme.textSecondary, marginTop: 6, fontSize: 15 },
  avatarSm: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.surfaceAlt,
    borderWidth: 1,
    borderColor: theme.border,
  },
  err: { color: theme.error, marginBottom: 12 },
  statsRow: { flexDirection: "row", gap: 10, marginBottom: 20 },
  statSk: { flex: 1, height: 88, borderRadius: 12 },
  scoreCardSk: { height: 160, borderRadius: 16, marginBottom: 24 },
  statPress: { flex: 1 },
  statCard: {
    flex: 1,
    backgroundColor: theme.surfaceAlt,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: theme.border,
  },
  statVal: {
    color: theme.textPrimary,
    fontSize: 20,
    fontWeight: "800",
    marginTop: 6,
  },
  statLab: { color: theme.textMuted, fontSize: 11, marginTop: 4 },
  atsCard: {
    flexDirection: "row",
    backgroundColor: theme.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: theme.border,
    gap: 16,
  },
  emptyScoreCard: {
    backgroundColor: theme.surface,
    borderRadius: 16,
    padding: 24,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: theme.border,
    alignItems: "center",
  },
  emptyScoreTitle: {
    color: theme.textPrimary,
    fontWeight: "700",
    fontSize: 17,
    marginTop: 12,
  },
  emptyScoreSub: {
    color: theme.textSecondary,
    textAlign: "center",
    marginTop: 8,
    lineHeight: 22,
    fontSize: 15,
  },
  getStartedBtn: {
    marginTop: 16,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 14,
  },
  getStartedTxt: { color: "#FFFFFF", fontWeight: "700" },
  ringWrap: { justifyContent: "center" },
  atsTitle: { color: theme.textPrimary, fontWeight: "700", fontSize: 16 },
  tierPillWide: {
    alignSelf: "flex-start",
    marginTop: 8,
    marginBottom: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: theme.surfaceAlt,
    borderWidth: 1,
    borderColor: theme.border,
  },
  tierPillTxt: { color: theme.textSecondary, fontSize: 12, fontWeight: "600" },
  reportBtn: { paddingVertical: 12, borderRadius: 14, alignItems: "center" },
  reportBtnText: { color: "#FFFFFF", fontWeight: "700" },
  sectionTitle: {
    color: theme.textSecondary,
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginBottom: 12,
  },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: 12, marginBottom: 24 },
  actionCard: {
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.border,
    minHeight: 100,
    gap: 8,
  },
  actionLab: { color: theme.textPrimary, fontWeight: "600", fontSize: 14 },
  tipCard: {
    width: 260,
    backgroundColor: theme.surfaceAlt,
    borderRadius: 16,
    padding: 16,
    marginRight: 12,
    borderWidth: 1,
    borderColor: theme.border,
  },
  tipEmoji: { fontSize: 28, marginBottom: 8 },
  tipTitle: {
    color: theme.textPrimary,
    fontWeight: "700",
    marginBottom: 8,
    fontSize: 16,
  },
  tipBody: { color: theme.textSecondary, lineHeight: 22, fontSize: 14 },
  heroContainer: {
    overflow: "hidden",
    position: "relative",
    marginTop: 8,
    marginBottom: 20,
    paddingBottom: 4,
  },
  heroGlow: {
    position: "absolute",
    top: -80,
    right: -60,
    width: 220,
    height: 220,
    borderRadius: 110,
  },
  heroRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  heroLeft: {},
  heroEyebrow: {
    fontSize: 10,
    fontWeight: "600",
    color: theme.textSecondary,
    letterSpacing: 2,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  heroTitle: {
    fontSize: 26,
    fontWeight: "700",
    color: theme.textPrimary,
    letterSpacing: -0.8,
    lineHeight: 30,
  },
  heroNameAccent: { color: theme.primary },
  heroSub: {
    fontSize: 13,
    color: theme.textSecondary,
    marginTop: 4,
    opacity: 0.8,
    lineHeight: 18,
  },
  heroRight: { alignItems: "flex-end", gap: 6 },
  avatarRing: {
    width: 46,
    height: 46,
    borderRadius: 23,
    overflow: "hidden",
    padding: 2,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  avatarImage: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: theme.surfaceAlt,
  },
  avatarFallback: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: theme.surfaceAlt,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.04)",
  },
  avatarInitials: {
    fontSize: 15,
    fontWeight: "700",
    color: theme.textPrimary,
  },
  creditsBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(0,212,170,0.1)",
    borderWidth: 1,
    borderColor: "rgba(0,212,170,0.2)",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  creditsGreenDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: theme.accent,
  },
  creditsText: { fontSize: 9, fontWeight: "600", color: theme.accent },
  });
}
