import { StyleSheet } from "react-native";
import { getElevation, type AppTheme } from "../../theme";

export function createHomeStyles(theme: AppTheme) {
  const elevation = getElevation(theme);
  const isLight = theme.background === "#F3F4F8";

  return StyleSheet.create({
  scroll: { flex: 1 },
  content: { paddingHorizontal: 20, paddingBottom: 40 },
  screenTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: theme.textPrimary,
    letterSpacing: -0.5,
    marginBottom: 8,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
    marginBottom: 20,
  },
  greet: {
    color: theme.textPrimary,
    fontSize: 22,
    fontWeight: "800",
    letterSpacing: -0.5,
  },
  subGreet: { color: theme.textSecondary, marginTop: 6, fontSize: 15 },
  avatarSm: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.surfaceAlt,
    borderWidth: 1,
    borderColor: theme.border,
  },
  err: { color: theme.error, marginBottom: 12 },
  statsRow: { flexDirection: "row", gap: 10, marginBottom: 20 },
  statSk: { flex: 1, height: 88, borderRadius: 12 },
  scoreCardSk: { height: 160, borderRadius: 16, marginBottom: 24 },
  statPress: { flex: 1 },
  statCard: {
    flex: 1,
    backgroundColor: theme.surface,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: theme.border,
    ...elevation.subtle,
  },
  statVal: {
    color: theme.textPrimary,
    fontSize: 20,
    fontWeight: "800",
    marginTop: 6,
  },
  statLab: { color: theme.textMuted, fontSize: 11, marginTop: 4 },
  atsCard: {
    flexDirection: "row",
    backgroundColor: theme.surface,
    borderRadius: 20,
    padding: 18,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: theme.border,
    gap: 16,
    ...elevation.card,
  },
  emptyScoreCard: {
    backgroundColor: theme.surface,
    borderRadius: 20,
    padding: 24,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: theme.border,
    alignItems: "center",
    ...elevation.card,
  },
  emptyScoreTitle: {
    color: theme.textPrimary,
    fontWeight: "700",
    fontSize: 17,
    marginTop: 12,
  },
  emptyScoreSub: {
    color: theme.textSecondary,
    textAlign: "center",
    marginTop: 8,
    lineHeight: 22,
    fontSize: 15,
  },
  getStartedBtn: {
    marginTop: 16,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 14,
  },
  getStartedTxt: { color: theme.onPrimary, fontWeight: "700" },
  ringWrap: { justifyContent: "center" },
  atsTitle: { color: theme.textPrimary, fontWeight: "700", fontSize: 16 },
  tierPillWide: {
    alignSelf: "flex-start",
    marginTop: 8,
    marginBottom: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: theme.surfaceAlt,
    borderWidth: 1,
    borderColor: theme.border,
  },
  tierPillTxt: { color: theme.textSecondary, fontSize: 12, fontWeight: "600" },
  reportBtn: { paddingVertical: 12, borderRadius: 14, alignItems: "center" },
  reportBtnText: { color: theme.onPrimary, fontWeight: "700" },
  sectionTitle: {
    color: theme.textSecondary,
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginBottom: 12,
  },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: 12, marginBottom: 24 },
  actionCard: {
    backgroundColor: theme.surface,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.border,
    minHeight: 100,
    gap: 8,
    ...elevation.subtle,
  },
  actionLab: { color: theme.textPrimary, fontWeight: "600", fontSize: 14 },
  tipCard: {
    width: 260,
    backgroundColor: theme.surface,
    borderRadius: 18,
    padding: 16,
    marginRight: 12,
    borderWidth: 1,
    borderColor: theme.border,
    ...elevation.subtle,
  },
  tipEmoji: { fontSize: 28, marginBottom: 8 },
  tipTitle: {
    color: theme.textPrimary,
    fontWeight: "700",
    marginBottom: 8,
    fontSize: 16,
  },
  tipBody: { color: theme.textSecondary, lineHeight: 22, fontSize: 14 },
  });
}
