import { Platform, StyleSheet } from "react-native";
import { colors } from "../../../theme/color";

export const resumeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "ios" ? 50 : 20,
    paddingBottom: 16,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.textPrimary,
    textAlign: "center",
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 40,
  },
  loadingIconWrapper: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: colors.accent + "12",
    borderWidth: 1,
    borderColor: colors.accent + "25",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 32,
  },
  loadingTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: colors.textPrimary,
    textAlign: "center",
    marginBottom: 10,
    letterSpacing: -0.3,
  },
  loadingSubtitle: {
    fontSize: 15,
    color: colors.textSecondary,
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 32,
  },
  loadingDots: {
    flexDirection: "row",
    gap: 8,
  },
  loadingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "rgba(255,255,255,0.15)",
  },
  loadingDotActive: {
    backgroundColor: colors.accent,
    width: 24,
  },
  progressBarContainer: {
    width: "100%",
    height: 3,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: 2,
    marginBottom: 6,
    marginTop: 8,
  },
  progressBarFill: {
    height: 3,
    borderRadius: 2,
    backgroundColor: colors.accent,
  },
  stepMeta: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  stepMetaText: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  stepMetaTitle: {
    fontSize: 12,
    color: colors.accent,
    fontWeight: "600",
  },
  stepTitleCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    padding: 16,
    marginBottom: 20,
  },
  stepIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.accent + "15",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.accent + "30",
  },
  stepTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: colors.textPrimary,
    letterSpacing: -0.3,
    marginBottom: 3,
  },
  stepSubtitle: {
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 18,
  },
  formCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    padding: 20,
    marginBottom: 20,
  },
  fieldGroup: {
    marginBottom: 16,
  },
  fieldLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.textSecondary,
    letterSpacing: 0.5,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  required: {
    color: colors.accent,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.bgSecondary,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 14,
    height: 52,
  },
  inputIcon: {
    marginRight: 10,
  },
  inputWithIcon: {
    flex: 1,
    fontSize: 15,
    color: colors.textPrimary,
    height: "100%",
  },
  inputWrapperMultiline: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: colors.bgSecondary,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 14,
    paddingTop: 14,
    minHeight: 100,
  },
  inputMultiline: {
    flex: 1,
    fontSize: 15,
    color: colors.textPrimary,
    textAlignVertical: "top",
  },
  fieldHint: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 4,
  },
  pillGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 4,
  },
  pill: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.bgSecondary,
  },
  pillSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  pillText: {
    fontSize: 13,
    fontWeight: "500",
    color: colors.textSecondary,
  },
  pillTextSelected: {
    color: "#fff",
    fontWeight: "700",
  },
  expCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    padding: 16,
    marginBottom: 12,
  },
  expCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
  },
  expCardNumber: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.accent + "20",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.accent + "40",
  },
  expCardNumberText: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.accent,
  },
  expCardTitle: {
    flex: 1,
    fontSize: 14,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  expDeleteBtn: {
    padding: 4,
  },
  addRoleBtn: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.accent + "30",
    borderStyle: "dashed",
    marginBottom: 16,
    overflow: "hidden",
  },
  addRoleBtnInner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: 16,
    backgroundColor: colors.accent + "08",
  },
  addRoleBtnText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.accent,
  },
  navButtons: {
    flexDirection: "row",
    gap: 12,
    paddingTop: 8,
    paddingBottom: 32,
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    height: 56,
    paddingHorizontal: 20,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.bgSecondary,
    justifyContent: "center",
  },
  backButtonText: {
    fontSize: 15,
    color: colors.textSecondary,
    fontWeight: "500",
  },
  nextButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    height: 56,
    borderRadius: 16,
    backgroundColor: colors.primary,
  },
  nextButtonDisabled: {
    opacity: 0.4,
  },
  nextButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#fff",
  },
  scrollContent: {
    flex: 1,
  },
  scrollContentContainer: {
    padding: 20,
    paddingBottom: 0,
  },
  resultsScroll: {
    flex: 1,
  },
  resultsContent: {
    padding: 20,
  },
  resultCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    padding: 20,
    marginBottom: 16,
  },
  resultTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.textPrimary,
    marginBottom: 4,
  },
  resultSubtitle: {
    fontSize: 14,
    fontWeight: "500",
    color: colors.accent,
    marginBottom: 8,
  },
  resultMeta: {
    fontSize: 12,
    color: colors.textSecondary,
    marginBottom: 8,
  },
  bulletRow: {
    flexDirection: "row",
    marginBottom: 3,
  },
  bullet: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.accent,
    marginRight: 8,
    marginTop: 7,
  },
  bulletText: {
    flex: 1,
    fontSize: 14,
    color: colors.textPrimary,
    lineHeight: 20,
  },
  skillRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  eduEntry: {
    flexDirection: "row",
    marginBottom: 12,
  },
  eduLeft: {
    flex: 1,
  },
  eduDegree: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  eduInstitution: {
    fontSize: 14,
    color: colors.textSecondary,
    fontStyle: "italic",
    marginBottom: 4,
  },
  eduRight: {
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: "right",
  },
  infoNote: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(16, 185, 129, 0.1)",
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
  },
  infoNoteText: {
    fontSize: 13,
    color: colors.textPrimary,
    marginLeft: 8,
    flex: 1,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.textPrimary,
    marginBottom: 12,
  },
  cardContent: {
    fontSize: 14,
    color: colors.textPrimary,
    lineHeight: 20,
  },
  buttonRow: {
    flexDirection: "row",
    gap: 12,
  },
  primaryButton: {
    backgroundColor: colors.primary,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 24,
    alignItems: "center",
    flex: 1,
    height: 56,
  },
  primaryButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#fff",
  },
  ghostButton: {
    backgroundColor: "transparent",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 16,
    paddingHorizontal: 24,
    alignItems: "center",
    flex: 1,
    height: 56,
  },
  ghostButtonText: {
    fontSize: 16,
    fontWeight: "500",
    color: colors.textSecondary,
  },
  // Tab styles
  tabBar: {
    flexDirection: "row",
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 12,
    padding: 4,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  tab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
  },
  tabActive: {
    backgroundColor: colors.primary,
  },
  tabText: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.textSecondary,
  },
  tabTextActive: {
    color: "#fff",
  },
  // History styles
  historyLoadingContainer: {
    alignItems: "center",
    paddingVertical: 48,
    gap: 12,
  },
  historyLoadingText: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  emptyState: {
    alignItems: "center",
    paddingVertical: 48,
    paddingHorizontal: 24,
  },
  emptyIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.textPrimary,
    marginBottom: 8,
  },
  emptySubtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 24,
  },
  emptyAction: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: colors.primary,
  },
  emptyActionText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#fff",
  },
  historyCard: {
    marginBottom: 10,
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  historyCardInner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    backgroundColor: colors.surface,
    padding: 14,
  },
  historyCardIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: colors.accent + "15",
    borderWidth: 1,
    borderColor: colors.accent + "25",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  historyCardInfo: {
    flex: 1,
    gap: 4,
  },
  historyCardName: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.textPrimary,
    letterSpacing: -0.2,
  },
  historyCardRole: {
    fontSize: 13,
    color: colors.accent,
    fontWeight: "500",
  },
  historyCardMeta: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 4,
  },
  metaPill: {
    backgroundColor: "rgba(255,255,255,0.07)",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  metaPillText: {
    fontSize: 11,
    color: colors.textSecondary,
    fontWeight: "500",
  },
  metaPillAccent: {
    backgroundColor: colors.accent + "15",
    borderColor: colors.accent + "25",
  },
  metaPillAccentText: {
    color: colors.accent,
  },
  historyCardSkills: {
    fontSize: 11,
    color: colors.textMuted,
    marginTop: 2,
  },
  historyCardRight: {
    alignItems: "flex-end",
    justifyContent: "space-between",
    minHeight: 44,
  },
  historyCardDate: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  historyDeleteBtn: {
    padding: 2,
  },
  historyViewBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  historyViewBannerText: {
    fontSize: 14,
    color: colors.textSecondary,
    fontWeight: "500",
  },
});

// Export individual style groups if needed for specific components:
export const historyStyles = StyleSheet.create({
  // history-specific styles can be added here if needed
});

export const previewStyles = StyleSheet.create({
  // preview-specific styles can be added here if needed
});
