import { StyleSheet } from "react-native";
import { getElevation, type AppTheme } from "../../../theme";

export function createResumeStyles(theme: AppTheme) {
  const elevation = getElevation(theme);

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 20,
      height: 56,
      // No paddingTop — safe area is handled by the navigator/global provider
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: "700",
      color: theme.textPrimary,
      textAlign: "center",
      flex: 1,
    },
    loadingContainer: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 40,
      marginBottom: 60,
    },
    loadingIconWrapper: {
      width: 120,
      height: 120,
      borderRadius: 60,
      backgroundColor: theme.accent + "12",
      borderWidth: 1,
      borderColor: theme.accent + "25",
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 32,
    },
    loadingTitle: {
      fontSize: 22,
      fontWeight: "700",
      color: theme.textPrimary,
      textAlign: "center",
      marginVertical: 10,
      letterSpacing: -0.3,
    },
    loadingSubtitle: {
      fontSize: 15,
      color: theme.textSecondary,
      textAlign: "center",
      lineHeight: 22,
      marginBottom: 32,
    },
    loadingDots: {
      flexDirection: "row",
      gap: 8,
    },
    loadingDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.border,
    },
    loadingDotActive: {
      backgroundColor: theme.accent,
      width: 24,
    },
    progressBarContainer: {
      width: "100%",
      height: 3,
      backgroundColor: theme.surfaceAlt,
      borderRadius: 2,
      marginBottom: 6,
      marginTop: 8,
    },
    progressBarFill: {
      height: 3,
      borderRadius: 2,
      backgroundColor: theme.accent,
    },
    stepMeta: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 12,
    },
    stepMetaText: {
      fontSize: 12,
      color: theme.textSecondary,
    },
    stepMetaTitle: {
      fontSize: 12,
      color: theme.accent,
      fontWeight: "600",
    },
    stepTitleCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: 14,
      backgroundColor: theme.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 14,
      marginBottom: 16,
      ...elevation.subtle,
    },
    stepIconCircle: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: theme.accent + "15",
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: theme.accent + "30",
    },
    stepTitle: {
      fontSize: 17,
      fontWeight: "700",
      color: theme.textPrimary,
      letterSpacing: -0.3,
      marginBottom: 3,
    },
    stepSubtitle: {
      fontSize: 13,
      color: theme.textSecondary,
      lineHeight: 18,
    },
    formCard: {
      backgroundColor: theme.surface,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 16,
      marginBottom: 16,
      gap: 12,
      ...elevation.card,
    },
    fieldGroup: {
      marginBottom: 0,
    },
    fieldLabel: {
      fontSize: 12,
      fontWeight: "600",
      color: theme.textSecondary,
      letterSpacing: 0.5,
      textTransform: "uppercase",
      marginBottom: 8,
    },
    required: {
      color: theme.accent,
    },
    // ─── Input system ────────────────────────────────────────────────
    inputWrapper: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.bgSecondary,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: 12,
      height: 48,
      overflow: "hidden",
    },
    inputIconContainer: {
      width: 28,
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
    },
    inputIcon: {
      // kept for backward compat — use inputIconContainer instead
    },
    inputSingleLine: {
      flex: 1,
      fontSize: 15,
      color: theme.textPrimary,
      height: 48,
      paddingVertical: 0,
      paddingHorizontal: 4,
    },
    inputWithIcon: {
      // alias — kept for backward compat
      flex: 1,
      fontSize: 15,
      color: theme.textPrimary,
      height: "100%",
    },
    inputWrapperMultiline: {
      flexDirection: "row",
      alignItems: "flex-start",
      backgroundColor: theme.bgSecondary,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: 12,
      paddingTop: 12,
      paddingBottom: 12,
      minHeight: 96,
    },
    inputMultiline: {
      flex: 1,
      fontSize: 15,
      color: theme.textPrimary,
      textAlignVertical: "top",
      paddingHorizontal: 4,
      paddingVertical: 0,
      minHeight: 72,
    },
    fieldHint: {
      fontSize: 12,
      color: theme.textMuted,
      marginTop: 4,
    },
    pillGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginTop: 4,
    },
    pill: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.bgSecondary,
    },
    pillSelected: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
    pillText: {
      fontSize: 13,
      fontWeight: "500",
      color: theme.textSecondary,
    },
    pillTextSelected: {
      color: theme.onPrimary,
      fontWeight: "700",
    },
    expCard: {
      backgroundColor: theme.surface,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 16,
      marginBottom: 12,
      ...elevation.subtle,
    },
    expCardHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginBottom: 16,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    expCardNumber: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: theme.accent + "20",
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: theme.accent + "40",
    },
    expCardNumberText: {
      fontSize: 13,
      fontWeight: "700",
      color: theme.accent,
    },
    expCardTitle: {
      flex: 1,
      fontSize: 14,
      fontWeight: "600",
      color: theme.textPrimary,
    },
    expDeleteBtn: {
      padding: 4,
    },
    addRoleBtn: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.accent + "30",
      borderStyle: "dashed",
      marginBottom: 16,
      overflow: "hidden",
    },
    addRoleBtnInner: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      padding: 16,
      backgroundColor: theme.accent + "08",
    },
    addRoleBtnText: {
      fontSize: 14,
      fontWeight: "600",
      color: theme.accent,
    },
    navButtons: {
      flexDirection: "row",
      gap: 12,
    },
    backButton: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      height: 56,
      paddingHorizontal: 20,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.bgSecondary,
      justifyContent: "center",
    },
    backButtonText: {
      fontSize: 15,
      color: theme.textSecondary,
      fontWeight: "500",
    },
    nextButton: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      height: 56,
      borderRadius: 16,
      backgroundColor: theme.primary,
    },
    nextButtonDisabled: {
      opacity: 0.4,
    },
    nextButtonText: {
      fontSize: 16,
      fontWeight: "700",
      color: theme.onPrimary,
    },
    scrollContent: {
      flex: 1,
    },
    scrollContentContainer: {
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 0,
    },
    resultsScroll: {
      flex: 1,
    },
    resultsContent: {
      padding: 20,
    },
    resultCard: {
      backgroundColor: theme.surface,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 20,
      marginBottom: 16,
      ...elevation.card,
    },
    resultTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: theme.textPrimary,
      marginBottom: 4,
    },
    resultSubtitle: {
      fontSize: 14,
      fontWeight: "500",
      color: theme.accent,
      marginBottom: 8,
    },
    resultMeta: {
      fontSize: 12,
      color: theme.textSecondary,
      marginBottom: 8,
    },
    bulletRow: {
      flexDirection: "row",
      marginBottom: 3,
    },
    bullet: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: theme.accent,
      marginRight: 8,
      marginTop: 7,
    },
    bulletText: {
      flex: 1,
      fontSize: 14,
      color: theme.textPrimary,
      lineHeight: 20,
    },
    skillRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    eduEntry: {
      flexDirection: "row",
      marginBottom: 12,
    },
    eduLeft: {
      flex: 1,
    },
    eduDegree: {
      fontSize: 16,
      fontWeight: "600",
      color: theme.textPrimary,
    },
    eduInstitution: {
      fontSize: 14,
      color: theme.textSecondary,
      fontStyle: "italic",
      marginBottom: 4,
    },
    eduRight: {
      fontSize: 14,
      color: theme.textSecondary,
      textAlign: "right",
    },
    infoNote: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "rgba(16, 185, 129, 0.1)",
      borderRadius: 8,
      padding: 12,
      marginBottom: 16,
    },
    infoNoteText: {
      fontSize: 13,
      color: theme.textPrimary,
      marginLeft: 8,
      flex: 1,
    },
    cardTitle: {
      fontSize: 16,
      fontWeight: "700",
      color: theme.textPrimary,
      marginBottom: 12,
    },
    cardContent: {
      fontSize: 14,
      color: theme.textPrimary,
      lineHeight: 20,
    },
    buttonRow: {
      flexDirection: "row",
      gap: 12,
    },
    primaryButton: {
      backgroundColor: theme.primary,
      borderRadius: 16,
      paddingVertical: 16,
      paddingHorizontal: 24,
      alignItems: "center",
      flex: 1,
      height: 56,
    },
    primaryButtonText: {
      fontSize: 16,
      fontWeight: "700",
      color: theme.onPrimary,
    },
    ghostButton: {
      backgroundColor: "transparent",
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.border,
      paddingVertical: 16,
      paddingHorizontal: 24,
      alignItems: "center",
      flex: 1,
      height: 56,
    },
    ghostButtonText: {
      fontSize: 16,
      fontWeight: "500",
      color: theme.textSecondary,
    },
    // Preview-specific buttons — full width, no flex: 1 (used in vertical stack)
    previewPrimaryButton: {
      backgroundColor: theme.primary,
      borderRadius: 16,
      height: 56,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 12,
    },
    previewGhostButton: {
      backgroundColor: "transparent",
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.border,
      height: 56,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 8,
    },
    // Tab styles
    tabBar: {
      flexDirection: "row",
      backgroundColor: theme.surfaceAlt,
      borderRadius: 12,
      padding: 4,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: theme.border,
    },
    tab: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      paddingVertical: 10,
      borderRadius: 10,
    },
    tabActive: {
      backgroundColor: theme.primary,
    },
    tabText: {
      fontSize: 13,
      fontWeight: "600",
      color: theme.textSecondary,
    },
    tabTextActive: {
      color: theme.onPrimary,
    },
    // History styles
    historyLoadingContainer: {
      alignItems: "center",
      paddingVertical: 48,
      gap: 12,
    },
    historyLoadingText: {
      fontSize: 14,
      color: theme.textSecondary,
    },
    emptyState: {
      alignItems: "center",
      paddingVertical: 48,
      paddingHorizontal: 24,
    },
    emptyIconCircle: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: theme.surfaceAlt,
      borderWidth: 1,
      borderColor: theme.border,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 16,
    },
    emptyTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: theme.textPrimary,
      marginBottom: 8,
    },
    emptySubtitle: {
      fontSize: 14,
      color: theme.textSecondary,
      textAlign: "center",
      lineHeight: 20,
      marginBottom: 24,
    },
    emptyAction: {
      paddingHorizontal: 24,
      paddingVertical: 12,
      borderRadius: 12,
      backgroundColor: theme.primary,
    },
    emptyActionText: {
      fontSize: 14,
      fontWeight: "700",
      color: theme.onPrimary,
    },
    historyCard: {
      marginBottom: 10,
      borderRadius: 20,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: theme.border,
      ...elevation.card,
    },
    historyCardInner: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 12,
      backgroundColor: theme.surface,
      padding: 14,
    },
    historyCardIcon: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: theme.accent + "15",
      borderWidth: 1,
      borderColor: theme.accent + "25",
      alignItems: "center",
      justifyContent: "center",
      marginTop: 2,
    },
    historyCardInfo: {
      flex: 1,
      gap: 4,
    },
    historyCardName: {
      fontSize: 15,
      fontWeight: "700",
      color: theme.textPrimary,
      letterSpacing: -0.2,
    },
    historyCardRole: {
      fontSize: 13,
      color: theme.accent,
      fontWeight: "500",
    },
    historyCardMeta: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
      marginTop: 4,
    },
    metaPill: {
      backgroundColor: theme.surfaceAlt,
      borderRadius: 6,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderWidth: 1,
      borderColor: theme.border,
    },
    metaPillText: {
      fontSize: 11,
      color: theme.textSecondary,
      fontWeight: "500",
    },
    metaPillAccent: {
      backgroundColor: theme.accent + "15",
      borderColor: theme.accent + "25",
    },
    metaPillAccentText: {
      color: theme.accent,
    },
    historyCardSkills: {
      fontSize: 11,
      color: theme.textMuted,
      marginTop: 2,
    },
    historyCardRight: {
      alignItems: "flex-end",
      justifyContent: "space-between",
      minHeight: 44,
    },
    historyCardDate: {
      fontSize: 11,
      color: theme.textSecondary,
    },
    historyDeleteBtn: {
      padding: 2,
    },
    historyViewBanner: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: theme.surfaceAlt,
      borderRadius: 12,
      padding: 12,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: theme.border,
    },
    historyViewBannerText: {
      fontSize: 14,
      color: theme.textSecondary,
      fontWeight: "500",
    },
    fixedFooter: {
      paddingHorizontal: 20,
      paddingTop: 14,

      backgroundColor: theme.background,
      borderTopWidth: 1,
      borderTopColor: theme.border,
    },
  });
}
