import { StyleSheet } from "react-native";
import { getElevation, type AppTheme } from "../../theme";

export function createInterviewStyles(theme: AppTheme) {
  const elevation = getElevation(theme);

  return StyleSheet.create({
    flex: { flex: 1 },
    container: { flex: 1, backgroundColor: theme.background },

    setupScroll: { flex: 1 },
    setupContent: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 60 },
    setupHeaderWrap: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 4 },
    setupHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginBottom: 6,
    },
    setupIconCircle: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.primaryDark,
      alignItems: "center",
      justifyContent: "center",
    },
    setupTitle: {
      color: theme.textPrimary,
      fontSize: 22,
      fontWeight: "700",
    },
    setupSubtitle: {
      color: theme.textMuted,
      fontSize: 14,
      lineHeight: 20,
    },

    card: {
      backgroundColor: theme.surface,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 16,
      marginBottom: 12,
      ...elevation.card,
    },
    fieldLabel: {
      fontSize: 10,
      fontWeight: "700",
      color: theme.textSecondary,
      textTransform: "uppercase",
      letterSpacing: 1.5,
      marginBottom: 10,
    },
    roleInput: {
      backgroundColor: theme.surfaceAlt,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 12,
      color: theme.textPrimary,
      fontSize: 15,
    },
    roleInputFocused: { borderColor: theme.primary },
    pillRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },

    startButtonWrap: { marginTop: 24, width: "100%", alignSelf: "stretch" },
    startBtn: {
      width: "100%",
      height: 56,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
    },
    startBtnDisabled: { opacity: 0.4 },
    startBtnRow: { flexDirection: "row", alignItems: "center", gap: 10 },
    startBtnText: { color: theme.onPrimary, fontWeight: "700", fontSize: 16 },

    progressHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingTop: 12,
      paddingBottom: 8,
    },
    progressText: {
      color: theme.textSecondary,
      fontSize: 13,
      fontWeight: "500",
    },
    endBtn: {
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
    },
    endBtnText: { color: theme.textSecondary, fontWeight: "600", fontSize: 12 },
    progressTrack: {
      height: 3,
      borderRadius: 2,
      backgroundColor: theme.surfaceAlt,
      overflow: "hidden",
      marginHorizontal: 20,
      marginBottom: 16,
    },
    progressFill: { height: 3, borderRadius: 2 },

    questionCard: {
      backgroundColor: theme.surface,
      padding: 18,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.border,
      marginHorizontal: 20,
      marginBottom: 16,
      paddingLeft: 22,
      overflow: "hidden",
      position: "relative",
      ...elevation.card,
    },
    questionAccentBar: {
      position: "absolute",
      left: 0,
      top: 0,
      bottom: 0,
      width: 3,
      borderTopLeftRadius: 2,
      borderBottomLeftRadius: 2,
    },
    questionHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 12,
    },
    questionBadge: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: theme.primary,
      alignItems: "center",
      justifyContent: "center",
    },
    questionBadgeText: {
      color: theme.onPrimary,
      fontSize: 13,
      fontWeight: "700",
    },
    speakerBtn: {
      width: 36,
      height: 36,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: theme.border,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "transparent",
    },
    speakerBtnActive: {
      borderColor: theme.primary,
      backgroundColor: "rgba(139, 92, 246, 0.1)",
    },
    questionText: {
      color: theme.textPrimary,
      fontSize: 18,
      fontWeight: "600",
      lineHeight: 28,
    },
    metaRow: { flexDirection: "row", gap: 8, marginTop: 16 },
    metaChipPrimary: {
      backgroundColor: "rgba(108,99,255,0.15)",
      borderColor: theme.primary,
      borderWidth: 1,
      borderRadius: 24,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    metaChipTextPrimary: {
      color: theme.primary,
      fontWeight: "600",
      fontSize: 11,
    },
    metaChip: {
      borderWidth: 1,
      borderRadius: 24,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    metaChipText: { fontWeight: "600", fontSize: 11 },

    inputContainer: {
      paddingHorizontal: 20,
      paddingBottom: 20,
    },
    answerInput: {
      minHeight: 120,
      backgroundColor: theme.surfaceAlt,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 14,
      fontSize: 15,
      color: theme.textPrimary,
      textAlignVertical: "top",
    },
    answerInputFocused: {
      borderColor: theme.primary,
      borderWidth: 1.5,
    },
    answerInputRecording: {
      borderColor: theme.accent,
      borderWidth: 1.5,
    },
    inputActionsRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: 10,
      gap: 10,
    },
    charCount: {
      color: theme.textMuted,
      fontSize: 12,
    },
    inputButtonsRow: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    micBtn: {
      width: 48,
      height: 48,
      borderRadius: 24,
      borderWidth: 2,
      borderColor: theme.primary,
      backgroundColor: "rgba(139, 92, 246, 0.08)",
      alignItems: "center",
      justifyContent: "center",
    },
    micBtnRecording: {
      borderColor: theme.danger,
      backgroundColor: "rgba(239, 68, 68, 0.10)",
    },
    micBtnDisabled: {
      borderColor: theme.border,
      backgroundColor: "transparent",
      opacity: 0.45,
    },
    submitBtn: {
      flex: 1,
      height: 48,
      borderRadius: 14,
      overflow: "hidden",
    },
    submitBtnDisabled: { opacity: 0.45 },
    submitGrad: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 14,
    },
    submitText: { color: theme.onPrimary, fontWeight: "700", fontSize: 15 },

    recordingIndicator: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginTop: 8,
    },
    recordingDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.danger,
    },
    recordingText: {
      color: theme.textSecondary,
      fontSize: 12,
      fontWeight: "500",
    },

    feedbackContainer: {
      marginHorizontal: 20,
      marginBottom: 16,
    },
    feedbackCard: {
      backgroundColor: theme.surface,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 18,
      gap: 14,
      ...elevation.card,
    },
    feedbackHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    feedbackTitle: {
      color: theme.textPrimary,
      fontSize: 16,
      fontWeight: "700",
    },
    scoreBadge: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 12,
    },
    scoreBadgeText: {
      color: theme.onPrimary,
      fontSize: 14,
      fontWeight: "700",
    },
    feedbackOverall: {
      color: theme.textSecondary,
      fontSize: 14,
      lineHeight: 22,
    },
    feedbackSection: {
      backgroundColor: theme.surfaceAlt,
      borderRadius: 10,
      padding: 12,
      gap: 6,
    },
    feedbackSectionLabel: {
      color: theme.textMuted,
      fontSize: 10,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 1,
      marginBottom: 2,
    },
    feedbackItem: {
      color: theme.textSecondary,
      fontSize: 13,
      lineHeight: 20,
    },
    feedbackTipBox: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 8,
      backgroundColor: "rgba(139, 92, 246, 0.08)",
      borderRadius: 10,
      padding: 12,
      borderWidth: 1,
      borderColor: "rgba(139, 92, 246, 0.2)",
    },
    feedbackTipText: {
      flex: 1,
      color: theme.primaryLight,
      fontSize: 13,
      lineHeight: 20,
    },
    nextBtn: {
      height: 50,
      borderRadius: 14,
      overflow: "hidden",
      marginHorizontal: 20,
      marginBottom: 20,
    },
    nextBtnGrad: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 14,
    },
    nextBtnText: {
      color: theme.onPrimary,
      fontSize: 15,
      fontWeight: "600",
    },

    completeScroll: { flex: 1 },
    completeContent: {
      paddingHorizontal: 20,
      paddingTop: 8,
      paddingBottom: 60,
    },
    completeHeader: { alignItems: "center", marginBottom: 24 },
    completeRingWrap: { marginBottom: 12 },
    completeTitle: {
      color: theme.textPrimary,
      fontSize: 22,
      fontWeight: "800",
      marginBottom: 8,
    },
    completeSubtitle: {
      color: theme.textSecondary,
      fontSize: 15,
      lineHeight: 22,
      textAlign: "center",
    },
    resultCard: {
      backgroundColor: theme.surface,
      padding: 14,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: theme.border,
      marginBottom: 12,
      ...elevation.subtle,
    },
    resultCardHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 8,
    },
    resultNumber: { color: theme.textMuted, fontWeight: "700" },
    resultQuestion: {
      color: theme.textPrimary,
      fontWeight: "700",
      marginBottom: 8,
      fontSize: 15,
    },
    resultAnswer: {
      color: theme.textSecondary,
      marginBottom: 8,
      fontSize: 14,
      lineHeight: 20,
    },
    resultFeedbackBox: {
      backgroundColor: theme.surfaceAlt,
      padding: 12,
      borderRadius: 10,
    },
    resultFeedbackLabel: {
      color: theme.textMuted,
      fontSize: 11,
      marginBottom: 4,
      textTransform: "uppercase",
      letterSpacing: 1,
    },
    resultFeedbackText: { color: theme.accent, fontSize: 13, lineHeight: 20 },
    completeFooter: { marginTop: 8, gap: 12 },
    primaryButton: {
      paddingVertical: 16,
      borderRadius: 14,
      backgroundColor: theme.primary,
      alignItems: "center",
    },
    primaryButtonText: {
      color: theme.onPrimary,
      fontWeight: "700",
      fontSize: 16,
    },
    ghostButton: {
      paddingVertical: 16,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.border,
      alignItems: "center",
    },
    ghostButtonText: { color: theme.textPrimary, fontWeight: "600" },

    errorOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0,0,0,0.7)",
      alignItems: "center",
      justifyContent: "center",
      padding: 20,
    },
    errorCard: {
      backgroundColor: theme.surface,
      borderRadius: 20,
      padding: 24,
      alignItems: "center",
      width: "100%",
      maxWidth: 340,
      ...elevation.raised,
    },
    errorTitle: {
      color: theme.textPrimary,
      fontSize: 18,
      fontWeight: "600",
      textAlign: "center",
      marginTop: 16,
    },
    errorMessage: {
      color: theme.textSecondary,
      fontSize: 14,
      textAlign: "center",
      marginTop: 8,
      lineHeight: 20,
    },
    errorBtn: {
      marginTop: 16,
      backgroundColor: theme.primary,
      paddingHorizontal: 24,
      paddingVertical: 12,
      borderRadius: 12,
    },
    errorBtnText: {
      color: theme.onPrimary,
      fontSize: 16,
      fontWeight: "600",
    },

    loadingOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0,0,0,0.6)",
      alignItems: "center",
      justifyContent: "center",
    },
    loadingText: {
      color: theme.textSecondary,
      fontSize: 14,
      marginTop: 12,
    },
  });
}
