import { StyleSheet } from "react-native";
import { colors } from "../../theme/color";

export const styles = StyleSheet.create({
  // ─── shared ────────────────────────────────────────────────
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  pageTitle: {
    color: colors.textPrimary,
    fontSize: 28,
    fontWeight: "700",
    marginBottom: 16,
    letterSpacing: -0.5,
  },

  // ─── AtsScoreScreen ────────────────────────────────────────
  back: { flexDirection: "row", alignItems: "center", marginBottom: 16 },
  backText: { color: colors.textPrimary, fontSize: 16 },
  hero: { alignItems: "center", marginBottom: 24 },
  tierPill: {
    marginTop: 12,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
  },
  tierPillText: { color: colors.textPrimary, fontWeight: "700", fontSize: 13 },
  section: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginBottom: 8,
    marginTop: 8,
  },
  accHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderColor: colors.border,
  },
  accTitle: { flex: 1, color: colors.textPrimary, fontWeight: "700" },
  accBody: { paddingBottom: 12 },
  bullet: {
    color: colors.textSecondary,
    lineHeight: 22,
    marginBottom: 6,
    fontSize: 15,
  },
  summaryCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: colors.border,
  },
  summaryLabel: {
    color: colors.textMuted,
    fontSize: 11,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  summaryText: { color: colors.textSecondary, lineHeight: 24, fontSize: 15 },
  cta: {
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: "center",
    marginTop: 8,
  },
  ctaText: { color: colors.textPrimary, fontWeight: "800", fontSize: 16 },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    backgroundColor: colors.surfaceAlt,
  },
  chipGreen: { borderColor: colors.accent },
  chipRed: { borderColor: colors.danger },
  chipTextGreen: { color: colors.accent, fontSize: 12 },
  chipTextRed: { color: colors.danger, fontSize: 12 },

  // ─── ResumeScreen — layout ──────────────────────────────────
  root: { flex: 1, paddingHorizontal: 20, backgroundColor: colors.background },
  topProg: {
    position: "absolute",
    left: 0,
    right: 0,
    zIndex: 10,
    paddingHorizontal: 20,
  },
  progTrack: {
    height: 4,
    backgroundColor: colors.surfaceAlt,
    borderRadius: 4,
    overflow: "hidden",
  },
  progFill: { height: 4, backgroundColor: colors.accent, borderRadius: 4 },

  // ─── ResumeScreen — loading skeletons ──────────────────────
  loadingWrap: {
    flex: 1,
    paddingHorizontal: 20,
    backgroundColor: colors.background,
  },
  quickStatsSkWrap: {
    width: "100%",
    flexDirection: "row",
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    marginTop: 8,
  },
  quickStatsSkCell: { flex: 1, alignItems: "center" },
  quickStatsSkDivider: { borderLeftWidth: 1, borderLeftColor: colors.border },
  quickStatsSkNum: { width: "55%", height: 22 },
  quickStatsSkLab: { width: "70%", height: 12, marginTop: 10 },
  resumeSkList: { width: "100%", marginTop: 16 },
  resumeSkCard: {
    flexDirection: "row",
    gap: 14,
    padding: 16,
    borderRadius: 16,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 12,
  },
  resumeSkPdf: { width: 44, height: 52 },
  resumeSkTitle: { width: "72%", height: 14 },
  resumeSkMeta: { width: "44%", height: 10, marginTop: 6 },
  resumeSkPill: { width: "44%", height: 18, marginTop: 12 },
  resumeSkBtnRow: { flexDirection: "row", gap: 12, marginTop: 12 },
  resumeSkBtn: { flex: 1, height: 34 },

  // ─── ResumeScreen — empty state ────────────────────────────
  emptyScroll: {
    flexGrow: 1,
    paddingHorizontal: 20,
    backgroundColor: colors.background,
  },
  emptyIllustration: {
    alignItems: "center",
    marginTop: 8,
    marginBottom: 20,
  },
  emptyBadge: {
    alignItems: "center",
    gap: 6,
    alignSelf: "center",
    backgroundColor: "rgba(108,99,255,0.10)",
    borderWidth: 1,
    borderColor: "rgba(108,99,255,0.22)",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 5,
    marginBottom: 16,
  },
  emptyBadgeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.primary,
  },
  emptyBadgeTxt: {
    fontSize: 11,
    fontWeight: "600",
    color: colors.primary,
    letterSpacing: 0.3,
  },
  emptyHeading: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.textPrimary,
    textAlign: "center",
    letterSpacing: -0.3,
    marginBottom: 8,
  },
  emptySub: {
    fontSize: 13,
    color: colors.textSecondary,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 24,
    paddingHorizontal: 16,
  },
  emptyFeatureList: {
    gap: 8,
    marginBottom: 28,
  },
  emptyUploadBtn: {
    borderRadius: 14,
    overflow: "hidden",
    marginBottom: 12,
  },
  emptyUploadGradient: {
    height: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  emptyUploadTxt: {
    fontSize: 15,
    fontWeight: "700",
    color: "#fff",
  },
  emptySupportRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  emptySupportTxt: {
    fontSize: 11,
    color: "#404060",
  },
  emptySupportDot: {
    fontSize: 11,
    color: "#404060",
  },

  // ─── ResumeScreen — resume list ────────────────────────────
  analyzingBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 12,
    marginBottom: 12,
    backgroundColor: colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.border,
    flexDirection: "row",
    gap: 14,
  },
  pdfIcon: {
    width: 44,
    height: 52,
    borderRadius: 8,
    backgroundColor: colors.danger,
    alignItems: "center",
    justifyContent: "center",
  },
  pdfTxt: { color: colors.textPrimary, fontWeight: "800", fontSize: 11 },
  cardTitle: { color: colors.textPrimary, fontWeight: "700", fontSize: 16 },
  cardMeta: { color: colors.textMuted, fontSize: 12, marginTop: 4 },
  scorePill: {
    alignSelf: "flex-start",
    marginTop: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
  },
  scorePillOn: {
    borderColor: colors.accent,
    backgroundColor: colors.surfaceAlt,
  },
  scorePillOff: {
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
  },
  scorePillTxt: { fontWeight: "700", fontSize: 12, color: colors.accent },
  cardRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 12,
    flexWrap: "wrap",
  },
  outlineBtn: {
    borderWidth: 1,
    borderColor: colors.primary,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "transparent",
  },
  outlineBtnTxt: { color: colors.primary, fontWeight: "600", fontSize: 13 },
  fab: {
    position: "absolute",
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    overflow: "hidden",
    elevation: 6,
  },
  fabInner: { flex: 1, alignItems: "center", justifyContent: "center" },

  // ─── ResumeScreen — analyze modal ──────────────────────────
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 24,
    paddingBottom: 36,
    borderWidth: 1,
    borderColor: colors.border,
  },
  modalTitle: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 8,
  },
  modalSub: { color: colors.textSecondary, fontSize: 13, marginBottom: 8 },
  jdInput: {
    minHeight: 100,
    backgroundColor: colors.surfaceAlt,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 12,
    color: colors.textPrimary,
    textAlignVertical: "top",
    fontSize: 15,
  },
  modalCta: { paddingVertical: 16, borderRadius: 14, alignItems: "center" },
  modalCtaTxt: { color: colors.textPrimary, fontWeight: "800", fontSize: 16 },
  listHeader: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  resumeCountLabel: {
    color: colors.textMuted,
    fontSize: 12,
    marginTop: 2,
    fontWeight: "500",
  },
  uploadIconBtn: {
    borderRadius: 14,
    overflow: "hidden",
  },
  uploadIconBtnInner: {
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
  },
  analyzingPulse: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: colors.primary,
    opacity: 0.5,
  },
  analyzingTxt: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "600",
  },
  analyzingSubTxt: {
    color: colors.textMuted,
    fontSize: 11,
    marginTop: 1,
  },
});
