import { StyleSheet } from "react-native";
import type { AppTheme } from "../../theme";

export function createProfileStyles(theme: AppTheme) {
  return StyleSheet.create({
  root: { flex: 1, backgroundColor: theme.background },
  scrollContent: { paddingHorizontal: 20, paddingTop: 0 },

  heroWrap: { marginBottom: 18 },
  heroBanner: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    height: 120,
  },
  heroInner: { alignItems: "center", paddingTop: 26 },

  avatarOuter: { width: 96, height: 96, position: "relative" },
  avatarRing: {
    width: 96,
    height: 96,
    borderRadius: 48,
    padding: 2.5,
    overflow: "hidden",
    position: "absolute",
    top: 0,
    left: 0,
  },
  avatarSeparator: {
    position: "absolute",
    top: 2.5,
    left: 2.5,
    right: 2.5,
    bottom: 2.5,
    borderRadius: 46,
    backgroundColor: theme.background,
    padding: 2,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarImg: { width: 84, height: 84, borderRadius: 42 },
  avatarFallback: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: theme.surfaceAlt,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarInitials: { fontSize: 28, fontWeight: "700", color: theme.primary },
  avatarEditBtn: {
    position: "absolute",
    right: -4,
    bottom: -4,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: theme.primary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: theme.background,
  },

  heroNameContainer: {
    width: "100%",
    alignItems: "center",
    marginTop: 12,
  },
  heroName: {
    fontSize: 24,
    fontWeight: "700",
    color: theme.textPrimary,
    letterSpacing: -0.5,
    textAlign: "center",
    width: "100%",
    flexShrink: 1,
  },
  heroRole: {
    marginTop: 4,
    fontSize: 14,
    color: theme.textSecondary,
    textAlign: "center",
  },
  badgeRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
    justifyContent: "center",
  },
  planBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: "rgba(108,99,255,0.12)",
    borderWidth: 1,
    borderColor: "rgba(108,99,255,0.3)",
  },
  planBadgeText: {
    color: theme.primary,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  creditsBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: "rgba(0,212,170,0.12)",
    borderWidth: 1,
    borderColor: "rgba(0,212,170,0.3)",
  },
  creditsBadgeText: {
    color: theme.accent,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1,
  },
  avatarBusyRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 10,
  },
  avatarBusyText: { color: theme.textSecondary, fontSize: 12 },
  heroActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 16,
  },

  statsStrip: {
    backgroundColor: theme.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.border,
    marginTop: 5,
    paddingVertical: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 8,
  },
  statCell: { flex: 1, alignItems: "center" },
  statDivider: { width: 1, height: 32, backgroundColor: theme.border },
  statValue: {
    color: theme.textPrimary,
    fontSize: 26,
    fontWeight: "800",
    letterSpacing: -1,
  },
  statValueMuted: { color: theme.textSecondary },
  statBest: { color: theme.accent },
  statLabel: {
    marginTop: 4,
    color: theme.textSecondary,
    fontSize: 10,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },

  sectionCap: {
    color: theme.textSecondary,
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.5,
  },

  bioCard: {
    marginTop: 16,
    backgroundColor: theme.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.border,
    padding: 20,
  },
  bioHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  bioEditLink: { color: theme.primary, fontSize: 13, fontWeight: "600" },
  bioText: {
    marginTop: 12,
    color: theme.textPrimary,
    fontSize: 14,
    lineHeight: 22,
  },
  bioPlaceholder: { color: theme.textSecondary, fontStyle: "italic" },

  settingsCard: {
    marginTop: 16,
    backgroundColor: theme.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.border,
    overflow: "hidden",
  },
  settingsRow: {
    paddingHorizontal: 20,
    paddingVertical: 18,
    flexDirection: "row",
    alignItems: "center",
  },
  settingsIconBox: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  settingsIconNotif: { backgroundColor: "rgba(108,99,255,0.12)" },
  settingsIconPrivacy: { backgroundColor: "rgba(0,212,170,0.12)" },
  settingsIconTerms: { backgroundColor: "rgba(144,144,176,0.12)" },
  settingsLabel: {
    flex: 1,
    marginLeft: 14,
    color: theme.textPrimary,
    fontSize: 15,
    fontWeight: "500",
  },
  settingsDivider: {
    height: 1,
    backgroundColor: theme.border,
    marginLeft: 68,
  },

  dangerWrap: { marginTop: 16 },
  dangerRow: {
    backgroundColor: theme.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.border,
    marginHorizontal: 0,
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  dangerIconCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  dangerIconPrimaryBg: { backgroundColor: "rgba(108,99,255,0.12)" },
  dangerIconDangerBg: { backgroundColor: "rgba(255,92,92,0.12)" },
  signOutText: {
    flex: 1,
    color: theme.primary,
    fontSize: 15,
    fontWeight: "600",
  },
  deleteRow: { marginTop: 10, borderColor: "rgba(255,92,92,0.2)" },
  deleteText: {
    flex: 1,
    color: theme.danger,
    fontSize: 15,
    fontWeight: "500",
  },

  footerCaption: {
    textAlign: "center",
    color: theme.textSecondary,
    fontSize: 11,
    marginTop: 24,
    marginBottom: 8,
  },
  footerHeart: { color: theme.danger },

  labelsRole: {
    color: theme.textMuted,
    fontSize: 11,
    letterSpacing: 1.5,
    textTransform: "uppercase" as const,
    marginBottom: 6,
  },

  inputBase: {
    backgroundColor: theme.surfaceAlt,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: theme.textPrimary,
    fontSize: 16,
  },
  inputArea: {
    backgroundColor: theme.surfaceAlt,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: theme.textPrimary,
    fontSize: 16,
    minHeight: 100,
    textAlignVertical: "top" as const,
  },

  chipsBase: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.surface,
  },

  chipsActive: {
    borderColor: theme.primary,
    backgroundColor: theme.surfaceAlt,
  },

  chipsText: {
    color: theme.textSecondary,
    fontSize: 13,
  },

  chipsTextActive: {
    color: theme.textPrimary,
    fontWeight: "700" as const,
  },

  modalScrim: { flex: 1 },

  modalScrimFill: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.55)",
  },

  modalSheetWrap: {
    position: "absolute" as const,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: theme.surface,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingTop: 16,
    paddingHorizontal: 16,
    paddingBottom: 32,
    borderTopWidth: 1,
    borderColor: theme.border,
  },

  modalTitle: {
    color: theme.textPrimary,
    fontSize: 18,
    fontWeight: "700" as const,
    marginBottom: 12,
  },

  modalRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },

  modalRowActive: {
    backgroundColor: theme.surfaceAlt,
  },

  // ─── ADD THESE TO YOUR styles.ts StyleSheet.create({...}) ───────────────────

  // Hero "Edit Profile" pill button (sits below badges in ProfileHero)
  heroEditProfileBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 16,
    paddingHorizontal: 20,
    paddingVertical: 9,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(108,99,255,0.35)",
    backgroundColor: "rgba(108,99,255,0.08)",
  },
  heroEditProfileText: {
    color: theme.primary,
    fontSize: 13,
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  heroManagePlanBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 18,
    paddingVertical: 9,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(245,158,11,0.32)",
    backgroundColor: "rgba(245,158,11,0.10)",
  },
  heroManagePlanText: {
    color: theme.warning,
    fontSize: 13,
    fontWeight: "600",
    letterSpacing: 0.2,
  },

  // Sticky action bar at the bottom of the screen while editing
  editActionBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 20,
    paddingTop: 14,
    backgroundColor: theme.background, // or theme.surface
    borderTopWidth: 1,
    borderTopColor: theme.border,
  },
  editCancelBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.surfaceAlt,
  },
  editCancelText: {
    color: theme.textSecondary,
    fontSize: 15,
    fontWeight: "600",
  },
  editSaveBtn: {
    flex: 2,
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.primary,
  },
  editSaveText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  // Profile section styles
  sectionContainer: {
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    marginBottom: 8,
    overflow: "hidden",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.05)",
  },
  sectionHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  sectionIconCircle: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: theme.accent + "15",
    borderWidth: 1,
    borderColor: theme.accent + "25",
    alignItems: "center",
    justifyContent: "center",
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: theme.textPrimary,
    letterSpacing: -0.2,
  },
  viewAllBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  viewAllText: {
    fontSize: 13,
    color: theme.accent,
    fontWeight: "600",
  },
  resumeMiniCard: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingRight: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.04)",
  },
  resumeMiniCardLast: {
    borderBottomWidth: 0,
  },
  resumeMiniAccent: {
    width: 3,
    height: 36,
    borderRadius: 2,
    backgroundColor: theme.accent,
    marginHorizontal: 16,
  },
  resumeMiniContent: {
    flex: 1,
    gap: 3,
  },
  resumeMiniTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  resumeMiniName: {
    fontSize: 14,
    fontWeight: "700",
    color: theme.textPrimary,
    flex: 1,
  },
  resumeMiniDate: {
    fontSize: 11,
    color: theme.textMuted,
    marginLeft: 8,
  },
  resumeMiniRole: {
    fontSize: 12,
    color: theme.accent,
    fontWeight: "500",
  },
  resumeMiniSkills: {
    fontSize: 11,
    color: theme.textMuted,
    lineHeight: 16,
  },
  resumeEmptyCard: {
    alignItems: "center",
    padding: 32,
    gap: 8,
  },
  resumeEmptyText: {
    fontSize: 14,
    color: theme.textSecondary,
    fontWeight: "500",
  },
  resumeEmptyAction: {
    fontSize: 13,
    color: theme.accent,
    fontWeight: "600",
  },
  resumeLoadingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    gap: 10,
  },
  resumeLoadingText: {
    fontSize: 13,
    color: theme.textSecondary,
  },
  buildNewBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: 14,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.05)",
  },
  buildNewBtnText: {
    fontSize: 13,
    fontWeight: "600",
    color: theme.primary,
  },
  });
}
