import { StyleSheet } from "react-native";
import type { AppTheme } from "../../../theme";

export function createCardStyles(theme: AppTheme) {
  return StyleSheet.create({
  card: {
    backgroundColor: theme.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: theme.border,
    padding: 10,
    flexDirection: "row",
    gap: 14,
  },
  leftCol: {
    alignItems: "center",
    gap: 8,
  },
  pdfIconWrap: {
    width: 48,
    height: 56,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    borderWidth: 1,
    borderColor: "rgba(108,99,255,0.2)",
  },
  pdfLabel: {
    color: "#FFFFFF",
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 1,
  },
  scoreDot: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  scoreDotText: {
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: -0.5,
  },
  content: {
    flex: 1,
    gap: 6,
  },
  title: {
    color: theme.textPrimary,
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: -0.3,
    lineHeight: 20,
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 4,
  },
  metaText: {
    color: theme.textMuted,
    fontSize: 11,
  },
  metaDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: theme.textMuted,
    opacity: 0.4,
    marginHorizontal: 2,
  },
  scorePill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
    borderWidth: 1,
    backgroundColor: "rgba(0,0,0,0.2)",
  },
  scorePillDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
  },
  scorePillText: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  unscored: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: "rgba(0,0,0,0.2)",
  },
  unscoredText: {
    fontSize: 11,
    color: theme.textMuted,
    fontWeight: "500",
  },
  statusPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
    borderWidth: 1,
    backgroundColor: "rgba(0,0,0,0.2)",
  },
  statusText: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  viewBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(0,212,170,0.25)",
    backgroundColor: "rgba(0,212,170,0.07)",
  },
  viewBtnText: {
    color: theme.accent,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.1,
  },
  actions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 6,
    flexWrap: "wrap",
  },
  primaryBtn: {
    borderRadius: 10,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(108,99,255,0.3)",
  },
  primaryBtnInner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  primaryBtnText: {
    color: theme.primary,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.1,
  },
  secondaryBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(0,212,170,0.25)",
    backgroundColor: "rgba(0,212,170,0.07)",
  },
  secondaryBtnText: {
    color: theme.accent,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.1,
  },
  deleteBtn: {
    marginLeft: "auto",
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: "rgba(255,92,92,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,92,92,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  });
}
