import { StyleSheet } from "react-native";
import type { AppTheme } from "../../theme";

export function createAIStyles(theme: AppTheme) {
  return StyleSheet.create({
  root: { flex: 1 },
  flex: { flex: 1 },
  centered: { flex: 1, alignItems: "center", justifyContent: "center" },

  // ─── Header ───────────────────────────────────────────────
  headerWrap: { paddingHorizontal: 20, marginBottom: 10, paddingTop: 10 },
  headerTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerTitleRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  headerTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: theme.textPrimary,
    letterSpacing: -0.5,
  },
  headerSubtitle: { fontSize: 11, color: theme.textSecondary, marginTop: 6 },
  headerSubtitleSpark: { color: theme.primary, fontWeight: "700" },
  historyBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },

  // ─── Status dot ───────────────────────────────────────────
  statusDotWrap: {
    width: 14,
    height: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  statusDotRing: {
    position: "absolute",
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: theme.accent,
  },
  statusDotInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: theme.accent,
  },

  // ─── Tab switcher ─────────────────────────────────────────
  tabOuter: {
    flexDirection: "row",
    marginHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
    paddingBottom: 2,
  },
  tabItem: {
    flex: 1,
    paddingBottom: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  tabText: { fontSize: 14 },
  tabTextActive: { color: theme.textPrimary, fontWeight: "600" },
  tabTextMuted: { color: theme.textSecondary, fontWeight: "400" },
  tabUnderlineTrack: {
    position: "absolute",
    left: 0,
    bottom: 0,
    height: 2,
    borderRadius: 2,
    overflow: "hidden",
  },
  tabUnderline: {
    position: "absolute",
    bottom: 0,
    left: 0,
    height: 2,
    borderRadius: 2,
    overflow: "hidden",
  },

  // ─── Chat ─────────────────────────────────────────────────
  chatBody: { flex: 1 },
  chatEmptyOuter: { flex: 1, justifyContent: "space-between" },
  chatEmptyWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    paddingHorizontal: 20,
    paddingTop: 22,
  },
  chatEmptyAvatarGlow: {
    width: 120,
    height: 120,
    borderRadius: 60,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: theme.primary,
    shadowOpacity: 0.2,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 0 },
  },
  chatEmptyTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: theme.textPrimary,
    textAlign: "center",
    marginTop: 18,
  },
  chatEmptySubtitle: {
    fontSize: 13,
    color: theme.textSecondary,
    textAlign: "center",
    marginTop: 8,
    lineHeight: 19,
    maxWidth: 260,
  },
  chatSuggestionList: { width: "100%", marginTop: 18 },

  // ─── Suggestion chips ─────────────────────────────────────
  suggestionChip: {
    marginBottom: 10,
    backgroundColor: theme.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.border,
    overflow: "hidden",
  },
  suggestionChipInner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  suggestionChipSpark: {
    color: theme.primary,
    fontSize: 14,
    width: 18,
    textAlign: "center",
    fontWeight: "700",
  },
  suggestionChipText: {
    flex: 1,
    color: theme.textPrimary,
    fontSize: 13,
    fontWeight: "500",
  },

  // ─── Message bubbles ──────────────────────────────────────
  listContent: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 8 },
  bubbleWrap: { marginBottom: 10 },
  bubbleWrapUser: {
    alignSelf: "flex-end",
    alignItems: "flex-end",
    maxWidth: "75%",
  },
  bubbleWrapAi: {
    alignSelf: "flex-start",
    alignItems: "flex-start",
    maxWidth: "85%",
  },
  msgTime: { fontSize: 10, color: theme.textSecondary, marginTop: 4 },
  msgTimeRight: { textAlign: "right" },
  aiBubbleHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  aiBubbleMark: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: theme.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  aiBubbleMarkSpark: {
    color: theme.textPrimary,
    fontSize: 12,
    fontWeight: "700",
  },
  aiBubbleHeaderTextWrap: { flex: 1 },
  aiBubbleHeaderText: {
    color: theme.primary,
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.5,
  },
  userBubbleGrad: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 18,
    borderBottomRightRadius: 4,
    overflow: "hidden",
  },
  aiBubbleSurface: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: theme.surfaceAlt,
    borderRadius: 18,
    borderBottomLeftRadius: 4,
    borderWidth: 1,
    borderColor: theme.border,
  },
  userBubbleText: {
    color: theme.textPrimary,
    fontSize: 14,
    lineHeight: 22,
    fontWeight: "400",
  },
  aiBubbleText: {
    color: theme.textPrimary,
    fontSize: 14,
    lineHeight: 22,
    fontWeight: "400",
  },

  // ─── Typing indicator ─────────────────────────────────────
  typingRow: { paddingHorizontal: 20, marginBottom: 8 },
  typingBubble: { alignSelf: "flex-start", maxWidth: "85%" },
  typingDots: { flexDirection: "row", gap: 6 },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: theme.textSecondary,
  },

  // ─── Input bar ────────────────────────────────────────────
  inputRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 10,
    borderTopWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.surface,
  },
  input: {
    flex: 1,
    minHeight: 44,
    maxHeight: 100,
    backgroundColor: theme.surfaceAlt,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 12,
    color: theme.textPrimary,
    borderWidth: 1,
    borderColor: theme.border,
    fontSize: 14,
  },
  inputFocused: { borderColor: theme.primary },
  sendBtnBase: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: theme.border,
  },
  sendBtnDisabled: {
    backgroundColor: theme.surfaceAlt,
    borderColor: theme.border,
  },

  // ─── Interview setup ──────────────────────────────────────
  setupContainer: { paddingHorizontal: 20 },
  setupTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: theme.textPrimary,
    marginBottom: 8,
  },
  setupSubtitle: {
    fontSize: 13,
    color: theme.textSecondary,
    lineHeight: 18,
    marginBottom: 16,
  },
  setupCard: {
    backgroundColor: theme.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.border,
    padding: 16,
    marginBottom: 12,
  },
  fieldLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: theme.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 1.5,
    marginBottom: 10,
  },
  ivInput: {
    backgroundColor: theme.surfaceAlt,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
    padding: 12,
    color: theme.textPrimary,
    fontSize: 15,
  },
  ivInputFocused: { borderColor: theme.primary },

  // ─── Pills ────────────────────────────────────────────────
  pillRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  pillBase: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: "transparent",
  },
  pillOff: { backgroundColor: "transparent", borderColor: theme.border },
  pillSelectedPrimary: {
    backgroundColor: "rgba(108,99,255,0.15)",
    borderColor: theme.primary,
  },
  pillSelectedEasy: {
    backgroundColor: "rgba(0,212,170,0.15)",
    borderColor: theme.accent,
  },
  pillSelectedMedium: {
    backgroundColor: "rgba(255,179,71,0.15)",
    borderColor: theme.warning,
  },
  pillSelectedHard: {
    backgroundColor: "rgba(255,92,92,0.15)",
    borderColor: theme.danger,
  },
  pillTextBase: {
    fontSize: 12,
    fontWeight: "400",
    textTransform: "capitalize",
  },
  pillTextMuted: { color: theme.textSecondary, fontWeight: "400" },
  pillTextPrimary: { color: theme.primary, fontWeight: "600" },
  pillTextEasy: { color: theme.accent, fontWeight: "600" },
  pillTextMedium: { color: theme.warning, fontWeight: "600" },
  pillTextHard: { color: theme.danger, fontWeight: "600" },

  // ─── Start button ─────────────────────────────────────────
  startButtonWrap: { marginTop: 24, width: "100%", alignSelf: "stretch" },
  startBtnRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  startBtn: {
    width: "100%",
    height: 56,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  startBtnDisabledGrad: { opacity: 0.4 },
  startBtnText: { color: "#FFFFFF", fontWeight: "700", fontSize: 16 },

  // ─── Live session ─────────────────────────────────────────
  liveBody: { flex: 1, paddingHorizontal: 20 },
  progressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  progressText: { color: theme.textSecondary, fontSize: 13 },
  endBtn: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
  },
  endBtnText: { color: theme.textSecondary, fontWeight: "600", fontSize: 12 },
  progressTrack: {
    height: 3,
    borderRadius: 2,
    backgroundColor: theme.surfaceAlt,
    overflow: "hidden",
    marginBottom: 20,
  },
  progressFillGrad: { height: 3, borderRadius: 2 },
  questionCard: {
    backgroundColor: theme.surface,
    padding: 18,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.border,
    marginBottom: 16,
    paddingLeft: 22,
    overflow: "hidden",
    position: "relative",
  },
  questionAccentBar: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 3,
    borderTopLeftRadius: 2,
    borderBottomLeftRadius: 2,
  },
  questionText: {
    color: theme.textPrimary,
    fontSize: 18,
    fontWeight: "600",
    lineHeight: 28,
  },
  questionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  questionNumberBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: theme.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  questionNumberText: {
    color: theme.textPrimary,
    fontSize: 13,
    fontWeight: "700",
  },
  metaRow: { flexDirection: "row", gap: 8, marginTop: 16 },
  metaChipPrimary: {
    backgroundColor: "rgba(108,99,255,0.15)",
    borderColor: theme.primary,
    borderWidth: 1,
    borderRadius: 24,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  metaChip: {
    borderWidth: 1,
    borderRadius: 24,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  metaChipTextPrimary: {
    color: theme.primary,
    fontWeight: "600",
    fontSize: 11,
  },
  metaChipText: { fontWeight: "600", fontSize: 11 },
  skipText: { color: theme.textPrimary, fontWeight: "600" },
  skipButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.border,
  },
  actionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    marginTop: 16,
  },
  submitButton: { flex: 1, borderRadius: 14, overflow: "hidden" },
  submitButtonDisabled: { opacity: 0.45 },
  submitGrad: { paddingVertical: 14, alignItems: "center", borderRadius: 14 },
  submitText: { color: "#FFFFFF", fontWeight: "700", fontSize: 16 },

  // Voice mode styles
  voiceModeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  voiceModeText: {
    flex: 1,
    marginRight: 16,
  },
  voiceModeSubLabel: {
    color: theme.textSecondary,
    fontSize: 12,
    marginTop: 2,
  },

  // Answer input styles
  answerInput: {
    minHeight: 120,
    backgroundColor: theme.surfaceAlt,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
    padding: 14,
    fontSize: 15,
    color: theme.textPrimary,
    textAlignVertical: "top",
  },
  answerInputFocused: {
    borderColor: theme.primary,
    borderWidth: 1.5,
  },
  characterCounter: {
    color: theme.textMuted,
    fontSize: 12,
    textAlign: "right",
    marginTop: 8,
  },

  // Results styles
  resultsContent: { paddingHorizontal: 20, paddingTop: 8 },
  resultsHeader: { alignItems: "center", marginBottom: 24 },
  ringWrap: { marginBottom: 12 },
  resultTitle: {
    color: theme.textPrimary,
    fontSize: 22,
    fontWeight: "800",
    marginBottom: 8,
  },
  resultSubtitle: {
    color: theme.textSecondary,
    fontSize: 15,
    lineHeight: 22,
    textAlign: "center",
  },
  questionResult: {
    backgroundColor: theme.surface,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.border,
    marginBottom: 12,
  },
  questionResultHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  questionResultNumber: { color: theme.textMuted, fontWeight: "700" },
  scoreBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  scoreBadgeText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "700",
  },
  questionResultQuestion: {
    color: theme.textPrimary,
    fontWeight: "700",
    marginBottom: 8,
    fontSize: 15,
  },
  questionResultAnswer: {
    color: theme.textSecondary,
    marginBottom: 8,
    fontSize: 14,
    lineHeight: 20,
  },
  feedbackBox: {
    backgroundColor: theme.surfaceAlt,
    padding: 12,
    borderRadius: 10,
  },
  feedbackLabel: {
    color: theme.textMuted,
    fontSize: 11,
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  feedbackText: { color: theme.accent, fontSize: 13, lineHeight: 20 },
  resultsFooter: { marginTop: 8, gap: 12 },
  primaryButton: {
    paddingVertical: 16,
    borderRadius: 14,
    backgroundColor: theme.primary,
    alignItems: "center",
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 16,
  },
  ghostButton: {
    paddingVertical: 16,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.border,
    alignItems: "center",
  },
  ghostButtonText: { color: theme.textPrimary, fontWeight: "600" },

  // ─── Legacy (kept for any residual refs) ──────────────────
  seg: {
    flexDirection: "row",
    marginHorizontal: 20,
    marginBottom: 12,
    backgroundColor: theme.surface,
    borderRadius: 14,
    padding: 4,
    borderWidth: 1,
    borderColor: theme.border,
  },
  segActive: { borderRadius: 12, paddingVertical: 10, alignItems: "center" },
  segActiveText: { color: "#FFFFFF", fontWeight: "700" },
  segInactive: { borderRadius: 12, paddingVertical: 10, alignItems: "center" },
  segInactiveText: { color: theme.textMuted, fontWeight: "600" },
  });
}
